defaults: ../../dpo.yaml
dpo:
  val_period: 50
  max_num_steps: 100
policy:
  model_name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
  train_global_batch_size: 16
  train_micro_batch_size: 1
  max_total_sequence_length: 4096
  dtensor_cfg:
    cpu_offload: true
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: dpo-nanov3-30BA3B-2n8g-fsdp2-cpuoffload
  tensorboard:
    log_dir: tb_logs-dpo-nanov3-30BA3B-2n8g-fsdp2-cpuoffload
  mlflow:
    run_name: dpo-nanov3-30BA3B-2n8g-fsdp2-cpuoffload
cluster:
  gpus_per_node: 8
  num_nodes: 2
