# Model arguments
model_name_or_path: meta-llama/Llama-4-Maverick-17B-128E-Instruct
tokenizer_name_or_path: meta-llama/Llama-4-Maverick-17B-128E-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/meta-llama/Llama-4-Maverick-17B-128E-Instruct/peft-qlora/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/Josephgflowers--Finance-Instruct-500k.jsonl
max_seq_length: 4096
packing: false

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules: "all-linear"
lora_modules_to_save: ["lm_head", "embed_tokens"]
lora_r: 4
lora_alpha: 16

# Modality type
modality_type: "image"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42