# Model arguments
model_name_or_path: google/vit-huge-patch14-224-in21k #632m #google/vit-large-patch16-224 # 307m  # google/vit-base-patch16-224 # 86m
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: runs/vit-base-patch16-224

# Dataset arguments
train_dataset_id_or_path: /opt/ml/input/data/dataset/train_dataset.parquet
validation_dataset_id_or_path: /opt/ml/input/data/dataset/validation_dataset.parquet
#test_dataset_id_or_path: /opt/ml/input/data/dataset/test_dataset.parquet
#packing: true

# Training arguments
num_train_epochs: 5
per_device_train_batch_size: 512
per_device_eval_batch_size: 256
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
metric_for_best_model : "accuracy"
remove_unused_columns : False

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- "none"
save_strategy: "no" # "epoch"
seed: 42

# Hugging Face Hub 
push_to_hub: false
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save