# Model arguments
model_name_or_path: microsoft/Phi-3-mini-128k-instruct
tokenizer_name_or_path: microsoft/Phi-3-mini-128k-instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/microsoft/Phi-3-mini-128k-instruct/spectrum/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/Josephgflowers--Finance-Instruct-500k.jsonl
max_seq_length: 4096
packing: true

# Spectrum Config
spectrum_config_path: configs/spectrum/microsoft/snr_results_microsoft-Phi-3-mini-128k-instruct_unfrozenparameters_30percent.yaml

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42