#!/usr/bin/env python3
"""
SAMA SFT Training Workflow MCP Server
Generates templatized SageMaker training scripts for Supervised Fine-Tuning,
following the pattern established by finetune--openai--gpt-oss-20b.ipynb.
"""

import logging
import os
import sys
import warnings
from pathlib import Path
from typing import Any, Dict, Optional

warnings.filterwarnings("ignore")
os.environ["PYTHONWARNINGS"] = "ignore"

logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    stream=sys.stderr,
)

from fastmcp import FastMCP

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

mcp = FastMCP("sama-sft-training-workflow-mcp-server")


# ---------------------------------------------------------------------------
# Instance type recommendations
# ---------------------------------------------------------------------------

def _recommend_instance(param_count: Optional[int], strategy: str) -> str:
    """Recommend a SageMaker instance type based on model size and strategy."""
    if param_count is None:
        return "ml.g5.2xlarge"

    billions = param_count / 1e9

    if strategy == "peft":
        if billions <= 3:
            return "ml.g5.xlarge"
        if billions <= 8:
            return "ml.g5.2xlarge"
        if billions <= 14:
            return "ml.g5.4xlarge"
        if billions <= 20:
            return "ml.p4de.24xlarge"
        return "ml.p5.48xlarge"
    elif strategy == "spectrum":
        if billions <= 3:
            return "ml.g5.2xlarge"
        if billions <= 8:
            return "ml.g5.4xlarge"
        if billions <= 20:
            return "ml.p4de.24xlarge"
        return "ml.p5.48xlarge"
    else:  # full
        if billions <= 3:
            return "ml.g5.4xlarge"
        if billions <= 8:
            return "ml.p4de.24xlarge"
        return "ml.p5.48xlarge"


def _attn_for_instance(instance_type: str) -> str:
    """Return the correct attention implementation for a SageMaker instance type.

    - P5, P6 (H100/H200 class) → kernels-community/vllm-flash-attn3
    - G5, G6, G6e, P4, P4d, P4de → kernels-community/flash-attn2
    - Unknown / None → eager
    """
    if not instance_type:
        return "eager"
    it = instance_type.lower()
    if any(x in it for x in ["p5.", "p5e.", "p6."]):
        return "kernels-community/vllm-flash-attn3"
    if any(x in it for x in ["g5.", "g6.", "g6e.", "p4.", "p4d.", "p4de."]):
        return "kernels-community/flash-attn2"
    return "eager"


# ---------------------------------------------------------------------------
# Script template
# ---------------------------------------------------------------------------

SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""
🚀 Fine-tune `{model_id}` on Amazon SageMaker AI

Auto-generated by SAMA SFT Training Workflow MCP Server.
Strategy: {strategy_display}
"""

import os
import json
import boto3
import sagemaker
from sagemaker.modules.configs import (
    CheckpointConfig,
    Compute,
    OutputDataConfig,
    SourceCode,
    StoppingCondition,
)
from sagemaker.modules.configs import InputData
from sagemaker.modules.train import ModelTrainer
from getpass import getpass

# ---------------------------------------------------------------------------
# SageMaker session setup
# ---------------------------------------------------------------------------
region = boto3.Session().region_name
sess = sagemaker.Session(boto3.Session(region_name=region))
sagemaker_session_bucket = sess.default_bucket()
role = sagemaker.get_execution_role()

print(f"sagemaker role arn: {{role}}")
print(f"sagemaker bucket: {{sess.default_bucket()}}")
print(f"sagemaker session region: {{sess.boto_region_name}}")

# ---------------------------------------------------------------------------
# Model and dataset configuration
# ---------------------------------------------------------------------------
MODEL_ID = "{model_id}"
hf_token = getpass("Enter your HuggingFace token: ")

# ---------------------------------------------------------------------------
# Dataset - update uploaded_s3_uri to your S3 dataset location
# ---------------------------------------------------------------------------
dataset_name = "{dataset_name}"
uploaded_s3_uri = f"s3://{{sess.default_bucket()}}/dataset/{{dataset_name.replace('/', '--').replace('.', '-')}}.jsonl"

# ---------------------------------------------------------------------------
# Observability - MLflow tracking (optional)
# ---------------------------------------------------------------------------
MLFLOW_TRACKING_SERVER_ARN = None  # Set to your MLflow ARN or None

if MLFLOW_TRACKING_SERVER_ARN:
    reports_to = "mlflow"
else:
    reports_to = "tensorboard"

job_name = MODEL_ID.replace("/", "--").replace(".", "-")

if MLFLOW_TRACKING_SERVER_ARN:
    training_env = {{
        "MLFLOW_EXPERIMENT_NAME": f"{{job_name}}-exp",
        "MLFLOW_TAGS": json.dumps({{
            "source.job": "sm-training-jobs",
            "source.type": "sft",
            "source.framework": "pytorch"
        }}),
        "MLFLOW_TRACKING_URI": MLFLOW_TRACKING_SERVER_ARN,
        "MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING": "true",
        "HF_TOKEN": hf_token,
        "FI_EFA_USE_DEVICE_RDMA": "1",
        "NCCL_DEBUG": "INFO",
        "NCCL_SOCKET_IFNAME": "eth0",
        "FI_PROVIDER": "efa",
        "NCCL_PROTO": "simple",
        "NCCL_NET_GDR_LEVEL": "5",
    }}
else:
    training_env = {{
        "HF_TOKEN": hf_token,
        "FI_EFA_USE_DEVICE_RDMA": "1",
        "NCCL_DEBUG": "INFO",
        "NCCL_SOCKET_IFNAME": "eth0",
        "FI_PROVIDER": "efa",
        "NCCL_PROTO": "simple",
        "NCCL_NET_GDR_LEVEL": "5",
    }}

# ---------------------------------------------------------------------------
# Training strategy selection
# ---------------------------------------------------------------------------
{strategy_blocks}

# ---------------------------------------------------------------------------
# Resolve training image
# ---------------------------------------------------------------------------
pytorch_image_uri = sagemaker.image_uris.retrieve(
    framework="pytorch",
    region=sess.boto_session.region_name,
    version="2.8.0",
    instance_type=training_instance_type,
    image_scope="training",
)
print(f"Using image: {{pytorch_image_uri}}")

# ---------------------------------------------------------------------------
# Launch training job
# ---------------------------------------------------------------------------
source_code = SourceCode(
    source_dir="./sagemaker_code",
    command=f"bash sm_accelerate_train.sh {{' '.join(args)}}",
)

compute_configs = Compute(
    instance_type=training_instance_type,
    instance_count=training_instance_count,
    keep_alive_period_in_seconds=1800,
    volume_size_in_gb=300,
)

base_job_name = f"{{job_name}}-finetune"
output_path = f"s3://{{sess.default_bucket()}}/{{base_job_name}}"

model_trainer = ModelTrainer(
    training_image=pytorch_image_uri,
    source_code=source_code,
    base_job_name=base_job_name,
    compute=compute_configs,
    stopping_condition=StoppingCondition(max_runtime_in_seconds=18000),
    output_data_config=OutputDataConfig(
        s3_output_path=output_path,
    ),
    checkpoint_config=CheckpointConfig(
        s3_uri=os.path.join(
            output_path,
            dataset_name.replace("/", "--").replace(".", "-"),
            job_name,
            "checkpoints",
        ),
        local_path="/opt/ml/checkpoints",
    ),
    role=role,
    environment=training_env,
)

model_trainer.train(
    input_data_config=[
        InputData(
            channel_name="training",
            data_source=uploaded_s3_uri,
        )
    ],
    wait=False,
)
'''


# ---------------------------------------------------------------------------
# Strategy block builders
# ---------------------------------------------------------------------------

def _build_strategy_blocks(
    model_id: str,
    strategy: str,
    org: str,
    model_name: str,
    peft_instance: str,
    spectrum_instance: str,
    full_instance: str,
) -> str:
    """Build the strategy selection code blocks with active/commented sections."""
    peft_recipe = f"hf_recipes/{org}/{model_name}--vanilla-peft-qlora.yaml"
    spectrum_recipe = f"hf_recipes/{org}/{model_name}--vanilla-spectrum.yaml"
    full_recipe = f"hf_recipes/{org}/{model_name}--vanilla-full.yaml"

    peft_block = f'''\
args = [
    "--config",
    "{peft_recipe}",
    # "--run-eval"  # enable for small models to run eval + tune
]
training_instance_type = "{peft_instance}"
training_instance_count = 1'''

    spectrum_block = f'''\
args = [
    "--config",
    "{spectrum_recipe}",
    # "--run-eval"  # enable for small models
]
training_instance_type = "{spectrum_instance}"
training_instance_count = 1'''

    full_block = f'''\
args = [
    "--config",
    "{full_recipe}",
    # "--run-eval"  # enable for small models
]
training_instance_type = "{full_instance}"
training_instance_count = 1'''

    def _comment(block: str) -> str:
        return "\n".join(f"# {line}" if line.strip() else "#" for line in block.splitlines())

    if strategy == "peft":
        return (
            f"# For PeFT (active)\n{peft_block}\n\n"
            f"## For Spectrum\n{_comment(spectrum_block)}\n\n"
            f"## For Full-Finetuning\n{_comment(full_block)}"
        )
    elif strategy == "spectrum":
        return (
            f"## For PeFT\n{_comment(peft_block)}\n\n"
            f"# For Spectrum (active)\n{spectrum_block}\n\n"
            f"## For Full-Finetuning\n{_comment(full_block)}"
        )
    else:
        return (
            f"## For PeFT\n{_comment(peft_block)}\n\n"
            f"## For Spectrum\n{_comment(spectrum_block)}\n\n"
            f"# For Full-Finetuning (active)\n{full_block}"
        )


# ---------------------------------------------------------------------------
# MCP Tools
# ---------------------------------------------------------------------------


@mcp.tool()
def generate_training_script(
    model_id: str,
    strategy: str = "peft",
    dataset_name: str = "AI-MO--NuminaMath-CoT",
    param_count: Optional[int] = None,
    output_dir: str = "../supervised_finetuning",
) -> Dict[str, Any]:
    """
    Generate a SageMaker training script for a model and recipe.

    This is STEP 4 (final step) of the SFT workflow. Call this AFTER
    generate_sft_recipe has created the recipe YAML. Creates a Python script
    following the established SAMA notebook pattern: session setup, data config,
    strategy selection, ModelTrainer launch. Includes active code for the selected
    strategy and commented-out blocks for the other two strategies.

    WORKFLOW: search/filter → get_model_details → generate_sft_recipe → generate_training_script

    Args:
        model_id: HuggingFace model identifier (e.g. 'meta-llama/Llama-3.2-3B-Instruct').
        strategy: Active fine-tuning strategy - 'peft', 'spectrum', or 'full'.
        dataset_name: Dataset name for the training data.
        param_count: Model parameter count (for instance type recommendation). None uses defaults.
        output_dir: Base directory for writing the script.

    Returns:
        Dictionary with status, script path, and recommended instance types.
    """
    try:
        strategy = strategy.lower()
        if strategy not in {"peft", "spectrum", "full"}:
            return {"status": "error", "message": f"Invalid strategy '{strategy}'. Must be 'peft', 'spectrum', or 'full'."}

        if "/" in model_id:
            org, model_name = model_id.split("/", 1)
        else:
            org, model_name = "models", model_id

        # Recommend instances for each strategy
        peft_instance = _recommend_instance(param_count, "peft")
        spectrum_instance = _recommend_instance(param_count, "spectrum")
        full_instance = _recommend_instance(param_count, "full")

        strategy_display = {"peft": "PEFT/LoRA (QLoRA)", "spectrum": "Spectrum", "full": "Full Fine-Tuning"}[strategy]

        strategy_blocks = _build_strategy_blocks(
            model_id, strategy, org, model_name,
            peft_instance, spectrum_instance, full_instance,
        )

        script_content = SCRIPT_TEMPLATE.format(
            model_id=model_id,
            strategy_display=strategy_display,
            dataset_name=dataset_name,
            strategy_blocks=strategy_blocks,
        )

        # Write script
        safe_name = model_id.replace("/", "--").replace(".", "-")
        script_filename = f"finetune--{safe_name}.py"
        script_path = Path(output_dir) / script_filename
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(script_content, encoding="utf-8")

        logger.info(f"Training script written to {script_path}")

        return {
            "status": "success",
            "message": f"Training script generated for {model_id} with {strategy_display} strategy.",
            "script_path": str(script_path),
            "script_filename": script_filename,
            "active_strategy": strategy,
            "instance_recommendations": {
                "peft": peft_instance,
                "spectrum": spectrum_instance,
                "full": full_instance,
            },
            "active_instance_type": {"peft": peft_instance, "spectrum": spectrum_instance, "full": full_instance}[strategy],
            "next_step": "Workflow complete. Summarize everything created: recipe YAML path, training script path, recommended instance type. The user can now run the generated script to launch the SageMaker training job.",
        }

    except Exception as e:
        logger.error(f"Failed to generate training script: {e}")
        return {"status": "error", "message": f"Script generation failed: {e}"}


@mcp.tool()
def get_instance_recommendation(
    param_count: int,
    strategy: str = "peft",
) -> Dict[str, Any]:
    """
    Get SageMaker instance type recommendations for a model and strategy.

    Args:
        param_count: Model parameter count (raw number, e.g. 3000000000 for 3B).
        strategy: Fine-tuning strategy - 'peft', 'spectrum', or 'full'.

    Returns:
        Recommended instance type and reasoning.
    """
    try:
        strategy = strategy.lower()
        if strategy not in {"peft", "spectrum", "full"}:
            return {"status": "error", "message": f"Invalid strategy '{strategy}'."}

        instance = _recommend_instance(param_count, strategy)
        billions = param_count / 1e9
        attn = _attn_for_instance(instance)

        all_strategies = {}
        for s in ("peft", "spectrum", "full"):
            inst = _recommend_instance(param_count, s)
            all_strategies[s] = {
                "instance_type": inst,
                "attn_implementation": _attn_for_instance(inst),
            }

        return {
            "status": "success",
            "param_count": param_count,
            "param_count_billions": round(billions, 1),
            "strategy": strategy,
            "recommended_instance_type": instance,
            "recommended_attn_implementation": attn,
            "all_strategies": all_strategies,
        }
    except Exception as e:
        return {"status": "error", "message": f"Recommendation failed: {e}"}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    """Main entry point for the MCP server."""
    mcp.run(show_banner=False)


if __name__ == "__main__":
    main()
