# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
tokenizer_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B/spectrum/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/AI-MO--NuminaMath-CoT.jsonl
max_seq_length: 4096
packing: false

# Spectrum Config
spectrum_config_path: configs/spectrum/deepseek-ai/snr_results_deepseek-ai-DeepSeek-R1-Distill-Qwen-1.5B_unfrozenparameters_30percent.yaml

# Modality type
modality_type: "text"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42
