unfrozen_parameters:
- ^lm_head.weight$
- ^model.embed_tokens.weight$
# audio_tower.conv1 layers
# audio_tower.conv2 layers
# audio_tower.embed_positions layers
# audio_tower.layer_norm layers
# fc1 layers
- audio_tower.layers.29.fc1
- audio_tower.layers.30.fc1
- audio_tower.layers.28.fc1
- audio_tower.layers.31.fc1
- audio_tower.layers.27.fc1
- audio_tower.layers.26.fc1
- audio_tower.layers.25.fc1
- audio_tower.layers.24.fc1
- audio_tower.layers.23.fc1
# fc2 layers
- audio_tower.layers.25.fc2
- audio_tower.layers.27.fc2
- audio_tower.layers.24.fc2
- audio_tower.layers.26.fc2
- audio_tower.layers.28.fc2
- audio_tower.layers.23.fc2
- audio_tower.layers.29.fc2
- audio_tower.layers.30.fc2
- audio_tower.layers.22.fc2
# final_layer_norm layers
- audio_tower.layers.0.final_layer_norm
- audio_tower.layers.1.final_layer_norm
- audio_tower.layers.2.final_layer_norm
- audio_tower.layers.3.final_layer_norm
- audio_tower.layers.4.final_layer_norm
- audio_tower.layers.5.final_layer_norm
- audio_tower.layers.6.final_layer_norm
- audio_tower.layers.7.final_layer_norm
- audio_tower.layers.8.final_layer_norm
# input_layernorm layers
- language_model.model.layers.0.input_layernorm
- language_model.model.layers.1.input_layernorm
- language_model.model.layers.2.input_layernorm
- language_model.model.layers.3.input_layernorm
- language_model.model.layers.4.input_layernorm
- language_model.model.layers.5.input_layernorm
- language_model.model.layers.6.input_layernorm
- language_model.model.layers.7.input_layernorm
- language_model.model.layers.8.input_layernorm
# language_model.lm_head layers
# language_model.model.embed_tokens layers
# language_model.model.norm layers
# mlp.down_proj layers
- language_model.model.layers.24.mlp.down_proj
- language_model.model.layers.25.mlp.down_proj
- language_model.model.layers.23.mlp.down_proj
- language_model.model.layers.30.mlp.down_proj
- language_model.model.layers.27.mlp.down_proj
- language_model.model.layers.29.mlp.down_proj
- language_model.model.layers.28.mlp.down_proj
- language_model.model.layers.22.mlp.down_proj
- language_model.model.layers.2.mlp.down_proj
# mlp.gate_proj layers
- language_model.model.layers.28.mlp.gate_proj
- language_model.model.layers.29.mlp.gate_proj
- language_model.model.layers.27.mlp.gate_proj
- language_model.model.layers.4.mlp.gate_proj
- language_model.model.layers.26.mlp.gate_proj
- language_model.model.layers.5.mlp.gate_proj
- language_model.model.layers.6.mlp.gate_proj
- language_model.model.layers.30.mlp.gate_proj
- language_model.model.layers.25.mlp.gate_proj
# mlp.up_proj layers
- language_model.model.layers.6.mlp.up_proj
- language_model.model.layers.4.mlp.up_proj
- language_model.model.layers.7.mlp.up_proj
- language_model.model.layers.5.mlp.up_proj
- language_model.model.layers.3.mlp.up_proj
- language_model.model.layers.9.mlp.up_proj
- language_model.model.layers.10.mlp.up_proj
- language_model.model.layers.8.mlp.up_proj
- language_model.model.layers.2.mlp.up_proj
# multi_modal_projector.linear layers
# post_attention_layernorm layers
- language_model.model.layers.0.post_attention_layernorm
- language_model.model.layers.1.post_attention_layernorm
- language_model.model.layers.2.post_attention_layernorm
- language_model.model.layers.3.post_attention_layernorm
- language_model.model.layers.4.post_attention_layernorm
- language_model.model.layers.5.post_attention_layernorm
- language_model.model.layers.6.post_attention_layernorm
- language_model.model.layers.7.post_attention_layernorm
- language_model.model.layers.8.post_attention_layernorm
# self_attn.k_proj layers
- audio_tower.layers.5.self_attn.k_proj
- audio_tower.layers.3.self_attn.k_proj
- audio_tower.layers.4.self_attn.k_proj
- audio_tower.layers.16.self_attn.k_proj
- audio_tower.layers.14.self_attn.k_proj
- audio_tower.layers.2.self_attn.k_proj
- audio_tower.layers.0.self_attn.k_proj
- audio_tower.layers.12.self_attn.k_proj
- audio_tower.layers.6.self_attn.k_proj
- audio_tower.layers.1.self_attn.k_proj
- audio_tower.layers.13.self_attn.k_proj
- audio_tower.layers.7.self_attn.k_proj
- audio_tower.layers.11.self_attn.k_proj
- audio_tower.layers.17.self_attn.k_proj
- audio_tower.layers.19.self_attn.k_proj
- audio_tower.layers.8.self_attn.k_proj
- audio_tower.layers.18.self_attn.k_proj
- audio_tower.layers.9.self_attn.k_proj
- audio_tower.layers.10.self_attn.k_proj
# self_attn.o_proj layers
- language_model.model.layers.13.self_attn.o_proj
- language_model.model.layers.10.self_attn.o_proj
- language_model.model.layers.1.self_attn.o_proj
- language_model.model.layers.16.self_attn.o_proj
- language_model.model.layers.12.self_attn.o_proj
- language_model.model.layers.14.self_attn.o_proj
- language_model.model.layers.11.self_attn.o_proj
- language_model.model.layers.17.self_attn.o_proj
- language_model.model.layers.18.self_attn.o_proj
# self_attn.out_proj layers
- audio_tower.layers.0.self_attn.out_proj
- audio_tower.layers.1.self_attn.out_proj
- audio_tower.layers.26.self_attn.out_proj
- audio_tower.layers.25.self_attn.out_proj
- audio_tower.layers.22.self_attn.out_proj
- audio_tower.layers.28.self_attn.out_proj
- audio_tower.layers.15.self_attn.out_proj
- audio_tower.layers.24.self_attn.out_proj
- audio_tower.layers.20.self_attn.out_proj
# self_attn.q_proj layers
- audio_tower.layers.3.self_attn.q_proj
- audio_tower.layers.5.self_attn.q_proj
- audio_tower.layers.4.self_attn.q_proj
- audio_tower.layers.1.self_attn.q_proj
- audio_tower.layers.14.self_attn.q_proj
- audio_tower.layers.2.self_attn.q_proj
- audio_tower.layers.0.self_attn.q_proj
- audio_tower.layers.6.self_attn.q_proj
- audio_tower.layers.16.self_attn.q_proj
- audio_tower.layers.13.self_attn.q_proj
- audio_tower.layers.12.self_attn.q_proj
- audio_tower.layers.7.self_attn.q_proj
- audio_tower.layers.11.self_attn.q_proj
- audio_tower.layers.8.self_attn.q_proj
- audio_tower.layers.9.self_attn.q_proj
- audio_tower.layers.15.self_attn.q_proj
- audio_tower.layers.10.self_attn.q_proj
- audio_tower.layers.18.self_attn.q_proj
- audio_tower.layers.17.self_attn.q_proj
# self_attn.v_proj layers
- audio_tower.layers.0.self_attn.v_proj
- audio_tower.layers.3.self_attn.v_proj
- audio_tower.layers.1.self_attn.v_proj
- audio_tower.layers.26.self_attn.v_proj
- audio_tower.layers.27.self_attn.v_proj
- audio_tower.layers.4.self_attn.v_proj
- audio_tower.layers.2.self_attn.v_proj
- language_model.model.layers.0.self_attn.v_proj
- audio_tower.layers.25.self_attn.v_proj
- audio_tower.layers.24.self_attn.v_proj
- audio_tower.layers.22.self_attn.v_proj
- audio_tower.layers.20.self_attn.v_proj
- audio_tower.layers.8.self_attn.v_proj
- audio_tower.layers.28.self_attn.v_proj
- audio_tower.layers.21.self_attn.v_proj
- audio_tower.layers.7.self_attn.v_proj
- audio_tower.layers.19.self_attn.v_proj
- audio_tower.layers.11.self_attn.v_proj
- audio_tower.layers.12.self_attn.v_proj
# self_attn_layer_norm layers
- audio_tower.layers.0.self_attn_layer_norm
- audio_tower.layers.1.self_attn_layer_norm
- audio_tower.layers.2.self_attn_layer_norm
- audio_tower.layers.3.self_attn_layer_norm
- audio_tower.layers.4.self_attn_layer_norm
- audio_tower.layers.5.self_attn_layer_norm
- audio_tower.layers.6.self_attn_layer_norm
- audio_tower.layers.7.self_attn_layer_norm
- audio_tower.layers.8.self_attn_layer_norm
