# Model arguments
model_name_or_path: openai/gpt-oss-20b
tokenizer_name_or_path: openai/gpt-oss-20b
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: false
output_dir: /opt/ml/output/openai/gpt-oss-20b/spectrum/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/interstellarninja--hermes_reasoning_tool_use.jsonl
max_seq_length: 4096
packing: false

# Spectrum Config
mxfp4: true
spectrum_config_path: configs/spectrum/openai/snr_results_openai-gpt-oss-20b_unfrozenparameters_30percent.yaml

# Modality type
modality_type: "text"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to:
- mlflow
run_name: gpt-oss-20b-spectrum-open-r1--OpenR1-Math-220k-withthinking
save_strategy: "epoch"
seed: 42
