unfrozen_parameters:
- ^lm_head.weight$
- ^model.embed_tokens.weight$
# feed_forward.down_proj layers
- model.layers.6.feed_forward.down_proj
- model.layers.8.feed_forward.down_proj
- model.layers.10.feed_forward.down_proj
- model.layers.30.feed_forward.down_proj
- model.layers.28.feed_forward.down_proj
- model.layers.4.feed_forward.down_proj
- model.layers.12.feed_forward.down_proj
# feed_forward.gate_proj layers
- model.layers.10.feed_forward.gate_proj
- model.layers.8.feed_forward.gate_proj
- model.layers.30.feed_forward.gate_proj
- model.layers.12.feed_forward.gate_proj
- model.layers.28.feed_forward.gate_proj
- model.layers.14.feed_forward.gate_proj
- model.layers.24.feed_forward.gate_proj
# feed_forward.router layers
- model.layers.5.feed_forward.router
- model.layers.15.feed_forward.router
- model.layers.19.feed_forward.router
- model.layers.11.feed_forward.router
- model.layers.21.feed_forward.router
- model.layers.17.feed_forward.router
- model.layers.13.feed_forward.router
# feed_forward.shared_expert.down_proj layers
- model.layers.7.feed_forward.shared_expert.down_proj
- model.layers.3.feed_forward.shared_expert.down_proj
- model.layers.9.feed_forward.shared_expert.down_proj
- model.layers.11.feed_forward.shared_expert.down_proj
- model.layers.15.feed_forward.shared_expert.down_proj
- model.layers.13.feed_forward.shared_expert.down_proj
- model.layers.5.feed_forward.shared_expert.down_proj
# feed_forward.shared_expert.gate_proj layers
- model.layers.1.feed_forward.shared_expert.gate_proj
- model.layers.3.feed_forward.shared_expert.gate_proj
- model.layers.5.feed_forward.shared_expert.gate_proj
- model.layers.7.feed_forward.shared_expert.gate_proj
- model.layers.9.feed_forward.shared_expert.gate_proj
- model.layers.11.feed_forward.shared_expert.gate_proj
- model.layers.13.feed_forward.shared_expert.gate_proj
# feed_forward.shared_expert.up_proj layers
- model.layers.9.feed_forward.shared_expert.up_proj
- model.layers.15.feed_forward.shared_expert.up_proj
- model.layers.7.feed_forward.shared_expert.up_proj
- model.layers.11.feed_forward.shared_expert.up_proj
- model.layers.13.feed_forward.shared_expert.up_proj
- model.layers.3.feed_forward.shared_expert.up_proj
- model.layers.5.feed_forward.shared_expert.up_proj
# feed_forward.up_proj layers
- model.layers.12.feed_forward.up_proj
- model.layers.16.feed_forward.up_proj
- model.layers.8.feed_forward.up_proj
- model.layers.30.feed_forward.up_proj
- model.layers.28.feed_forward.up_proj
- model.layers.6.feed_forward.up_proj
- model.layers.18.feed_forward.up_proj
# input_layernorm layers
- model.layers.0.input_layernorm
- model.layers.1.input_layernorm
- model.layers.2.input_layernorm
- model.layers.3.input_layernorm
- model.layers.4.input_layernorm
- model.layers.5.input_layernorm
- model.layers.6.input_layernorm
- model.layers.7.input_layernorm
- model.layers.8.input_layernorm
- model.layers.9.input_layernorm
- model.layers.10.input_layernorm
- model.layers.11.input_layernorm
- model.layers.12.input_layernorm
- model.layers.13.input_layernorm
# lm_head layers
# model.embed_tokens layers
# model.norm layers
# post_attention_layernorm layers
- model.layers.0.post_attention_layernorm
- model.layers.1.post_attention_layernorm
- model.layers.2.post_attention_layernorm
- model.layers.3.post_attention_layernorm
- model.layers.4.post_attention_layernorm
- model.layers.5.post_attention_layernorm
- model.layers.6.post_attention_layernorm
- model.layers.7.post_attention_layernorm
- model.layers.8.post_attention_layernorm
- model.layers.9.post_attention_layernorm
- model.layers.10.post_attention_layernorm
- model.layers.11.post_attention_layernorm
- model.layers.12.post_attention_layernorm
- model.layers.13.post_attention_layernorm
# self_attn.k_proj layers
- model.layers.27.self_attn.k_proj
- model.layers.19.self_attn.k_proj
- model.layers.11.self_attn.k_proj
- model.layers.15.self_attn.k_proj
- model.layers.3.self_attn.k_proj
- model.layers.23.self_attn.k_proj
- model.layers.24.self_attn.k_proj
- model.layers.18.self_attn.k_proj
- model.layers.28.self_attn.k_proj
- model.layers.14.self_attn.k_proj
- model.layers.20.self_attn.k_proj
- model.layers.16.self_attn.k_proj
- model.layers.17.self_attn.k_proj
- model.layers.7.self_attn.k_proj
# self_attn.o_proj layers
- model.layers.6.self_attn.o_proj
- model.layers.8.self_attn.o_proj
- model.layers.3.self_attn.o_proj
- model.layers.4.self_attn.o_proj
- model.layers.14.self_attn.o_proj
- model.layers.16.self_attn.o_proj
- model.layers.18.self_attn.o_proj
- model.layers.13.self_attn.o_proj
- model.layers.5.self_attn.o_proj
- model.layers.9.self_attn.o_proj
- model.layers.12.self_attn.o_proj
- model.layers.22.self_attn.o_proj
- model.layers.1.self_attn.o_proj
- model.layers.20.self_attn.o_proj
# self_attn.q_proj layers
- model.layers.3.self_attn.q_proj
- model.layers.7.self_attn.q_proj
- model.layers.23.self_attn.q_proj
- model.layers.27.self_attn.q_proj
- model.layers.19.self_attn.q_proj
- model.layers.26.self_attn.q_proj
- model.layers.25.self_attn.q_proj
- model.layers.17.self_attn.q_proj
- model.layers.15.self_attn.q_proj
- model.layers.30.self_attn.q_proj
- model.layers.22.self_attn.q_proj
- model.layers.24.self_attn.q_proj
- model.layers.21.self_attn.q_proj
- model.layers.28.self_attn.q_proj
# self_attn.v_proj layers
- model.layers.29.self_attn.v_proj
- model.layers.18.self_attn.v_proj
- model.layers.26.self_attn.v_proj
- model.layers.28.self_attn.v_proj
- model.layers.22.self_attn.v_proj
- model.layers.30.self_attn.v_proj
- model.layers.25.self_attn.v_proj
- model.layers.0.self_attn.v_proj
- model.layers.17.self_attn.v_proj
- model.layers.20.self_attn.v_proj
- model.layers.12.self_attn.v_proj
- model.layers.16.self_attn.v_proj
- model.layers.15.self_attn.v_proj
- model.layers.10.self_attn.v_proj
