# Model arguments
model_name_or_path: openai/gpt-oss-20b
tokenizer_name_or_path: openai/gpt-oss-20b
model_revision: main
torch_dtype: bfloat16
attn_implementation: kernels-community/vllm-flash-attn3
bf16: true
tf32: false
output_dir: /opt/ml/model/openai-gpt-oss-20b-HuggingFaceH4-Multilingual-Thinking/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/HuggingFaceH4--Multilingual-Thinking.jsonl
max_seq_length: 2048
packing: true
packing_strategy: wrapped

# LoRA arguments
use_peft: true
lora_target_modules: "all-linear"
lora_modules_to_save: ["7.mlp.experts.gate_up_proj", "7.mlp.experts.down_proj", "15.mlp.experts.gate_up_proj", "15.mlp.experts.down_proj", "23.mlp.experts.gate_up_proj", "23.mlp.experts.down_proj"]
lora_r: 8
lora_alpha: 16

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 6
per_device_eval_batch_size: 6
gradient_accumulation_steps: 3
gradient_checkpointing: true
optim: adamw_torch_fused
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_grad_norm: 0.3
bf16: true
bf16_full_eval: true
tf32: false

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
  - mlflow
save_strategy: "epoch"
seed: 42