unfrozen_parameters:
- ^lm_head.weight$
- ^model.embed_tokens.weight$
# input_layernorm layers
- model.layers.0.input_layernorm
- model.layers.1.input_layernorm
- model.layers.2.input_layernorm
- model.layers.3.input_layernorm
- model.layers.4.input_layernorm
- model.layers.5.input_layernorm
- model.layers.6.input_layernorm
- model.layers.7.input_layernorm
- model.layers.8.input_layernorm
# lm_head layers
# mlp.down_proj layers
- model.layers.2.mlp.down_proj
- model.layers.3.mlp.down_proj
- model.layers.23.mlp.down_proj
- model.layers.4.mlp.down_proj
- model.layers.25.mlp.down_proj
- model.layers.26.mlp.down_proj
- model.layers.1.mlp.down_proj
- model.layers.24.mlp.down_proj
- model.layers.28.mlp.down_proj
# mlp.gate_up_proj layers
- model.layers.31.mlp.gate_up_proj
- model.layers.4.mlp.gate_up_proj
- model.layers.3.mlp.gate_up_proj
- model.layers.5.mlp.gate_up_proj
- model.layers.6.mlp.gate_up_proj
- model.layers.9.mlp.gate_up_proj
- model.layers.30.mlp.gate_up_proj
- model.layers.7.mlp.gate_up_proj
- model.layers.8.mlp.gate_up_proj
# model.embed_tokens layers
# model.norm layers
# post_attention_layernorm layers
- model.layers.0.post_attention_layernorm
- model.layers.1.post_attention_layernorm
- model.layers.2.post_attention_layernorm
- model.layers.3.post_attention_layernorm
- model.layers.4.post_attention_layernorm
- model.layers.5.post_attention_layernorm
- model.layers.6.post_attention_layernorm
- model.layers.7.post_attention_layernorm
- model.layers.8.post_attention_layernorm
# self_attn.o_proj layers
- model.layers.0.self_attn.o_proj
- model.layers.1.self_attn.o_proj
- model.layers.10.self_attn.o_proj
- model.layers.11.self_attn.o_proj
- model.layers.9.self_attn.o_proj
- model.layers.19.self_attn.o_proj
- model.layers.3.self_attn.o_proj
- model.layers.8.self_attn.o_proj
- model.layers.4.self_attn.o_proj
# self_attn.qkv_proj layers
- model.layers.23.self_attn.qkv_proj
- model.layers.24.self_attn.qkv_proj
- model.layers.22.self_attn.qkv_proj
- model.layers.26.self_attn.qkv_proj
- model.layers.27.self_attn.qkv_proj
- model.layers.25.self_attn.qkv_proj
- model.layers.28.self_attn.qkv_proj
- model.layers.29.self_attn.qkv_proj
- model.layers.31.self_attn.qkv_proj
