# Model arguments
model_name_or_path: Qwen/Qwen3-VL-4B-Instruct
processor_name_or_path: Qwen/Qwen3-VL-4B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: false
output_dir: /opt/ml/output/Qwen/Qwen3-VL-4B-Instruct/full-finetuning/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/HuggingFaceM4--DoclingMatix.jsonl
max_seq_length: 4096
packing: false

# Spectrum Config
spectrum_config_path: configs/spectrum/Qwen/snr_results_Qwen-Qwen3-VL-4B-Instruct_unfrozenparameters_15percent.yaml

# Modality type
modality_type: "image"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1
remove_unused_columns: false

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to:
- mlflow
run_name: Qwen3-VL-4B-Instruct-peft-qlora-HuggingFaceM4--DoclingMatix
save_strategy: "epoch"
seed: 42
