# Model arguments
model_name_or_path: Qwen/Qwen2-Audio-7B-Instruct
processor_name_or_path: Qwen/Qwen2-Audio-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/Qwen/Qwen2-Audio-7B-Instruct/full-finetuning/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/mesolitica--AudioSet-Audio-Instructions.jsonl
max_seq_length: 8192
packing: false

# Modality type
modality_type: "audio"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42
