# Model arguments
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
processor_name_or_path: Qwen/Qwen3-VL-2B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: false
output_dir: /opt/ml/checkpoints/Qwen/Qwen3-VL-2B-Instruct/peft-qlora/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/AI-4-Everyone--Visual-TableQA.jsonl
max_seq_length: 512
packing: false

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
# lora_modules_to_save: ["lm_head", "embed_tokens"]
lora_r: 4
lora_alpha: 16
lora_dropout: 0.05

# Modality type
modality_type: "image"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1
remove_unused_columns: false

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- mlflow
run_name: Qwen3-VL-2B-Instruct-peft-qlora-AI-4-Everyone--Visual-TableQA
save_strategy: "epoch"
seed: 42
