# Model arguments
model_name_or_path: Qwen/QwQ-32B
tokenizer_name_or_path: Qwen/QwQ-32B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: false
output_dir: /opt/ml/output/Qwen/QwQ-32B/full-finetuning/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/AI-MO--NuminaMath-CoT.jsonl
max_seq_length: 4096
packing: false

# Modality type
modality_type: "text"

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to:
- mlflow
run_name: QwQ-32B-full-AI-MO--NuminaMath-CoT
save_strategy: "epoch"
seed: 42
