# Model arguments
model_name_or_path: HuggingFaceTB/SmolVLM-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: /opt/ml/model/vlm-sft-SmolVLM-Instruct-mini

# Dataset arguments
dataset_name: /opt/ml/input/data/dataset.hf/

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules:  ["down_proj", "o_proj", "k_proj", "q_proj", "gate_proj", "up_proj, v_proj"] # "all_linear" #["q_proj", "v_proj"]
# important as we need to train the special tokens for the chat template of llama 
#lora_modules_to_save: ["lm_head", "embed_tokens"] # you might need to change this for qwen or other models
lora_r: 16
lora_alpha: 16

# Training arguments
max_grad_norm: 0.3
num_train_epochs: 15
per_device_train_batch_size: 32
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
#optim: "adamw_torch_fused"
learning_rate: 5.0e-6 
lr_scheduler_type: constant
warmup_ratio: 0.03
eval_strategy: "epoch"

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- 'none'
save_strategy: "no"
seed: 42

# Hugging Face Hub 
push_to_hub: false
  # hub_model_id:  # if not defined same as output_dir
hub_strategy: every_save